### ISSUE TITLE
http -> https

### ISSUE THREAD

**Issue by drmjc** [hartwigmedical/scripts#1]
Hi Jon,
R CMD INSTALL (v3.3.2) breaks with this URL on L15. If you change to https, then R CMD INSTALL is happy.

https://github.com/hartwigmedical/scripts/blob/79e01afa8561f7f341ae6b71bdae12a91f78af31/purple/R/mutationalSignatures.R#L15

cheers,
Mark

**Comment by jonbaber** [comment]
Thanks for the heads up!

Have made the suggested change.
