### ISSUE TITLE
create_gridss_pon Column Name Error

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/scripts#3]
I have used callVariants to identify variants for a group of 10 healthy samples from non-cancer patients and it has created a VCF. Next, I used the R script create_gridss_pon in preparation for the gridss_somatic_filter script. However, it stops with an error

```r
Error: logical subscript contains NAs
In addition: Warning messages:
1: Unknown or uninitialised column: 'samples'. 
2: Unknown or uninitialised column: 'samples'. 
```

I wonder if `--normalordinal 1:10` is OK. I'm sure that it worked at some time in the past but it doesn't seem to work presently. Is there a plan to translate these loose R scripts into Java so they're part of GRIDSS and therefore versioned? If they were versioned, it would reduce the likelihood of incompatibilities creeping in. @d-cameron

**Comment by d-cameron** [comment]
Tracking as part of https://github.com/PapenfussLab/gridss/issues/230

**Comment by DarioS** [comment]
I am using R 3.6 and the latest scripts and installed Bioconductor packages but I continue to experience

```
Start load /project/DNAsequencing/structuralVariants/AllHealthy.vcf.gz
Error: logical subscript contains NAs
In addition: Warning messages:
1: Unknown or uninitialised column: 'samples'. 
2: Unknown or uninitialised column: 'samples'.
```

Also, it was using about 40 GB RAM for R when it ended, which seems a lot for processing a 792 MB VCF GZipped file.

**Comment by DarioS** [comment]
In other communication, it has been established that `create_gridss_pon.R` should not be used for a VCF file containing all normal samples but rather filtering and export into BED and BEDPE should be done using StructuralVariantAnnotation.
