### ISSUE TITLE
Recreating plots pan-cancer paper

### ISSUE THREAD

**Issue by willemdek11** [hartwigmedical/scripts#4]
Hey,

I would like to create the same plots that are shown in the paper, but could I use the scripts without connection to your database?

How would I create the .Rdata files that you're using, or could you give me some indication what they should look like?

Thanks,
Willem

**Comment by jonbaber** [comment]
My apologies for the late reply. The scripts are all contained in the [pancancerpaper](https://github.com/hartwigmedical/scripts/tree/master/pancancerpaper) directory. The cohort.R file is used to generate the .RData files the figures are based on and they typically match our [database schema](https://github.com/hartwigmedical/hmftools/blob/master/patient-db/src/main/resources/generate_database.sql).
